### ISSUE TITLE
RFE Add ability to handle multiple changes

### ISSUE THREAD

**Issue by trown** [redhat-openstack/ansible-role-tripleo-gate#2]
We need to be able to handle depends-on when gating.

I am not sure what the best way to parse env variables from zuul is, but for local testing, it would be nice if we could pass a list of projects/refspecs and have this role build all changes.

It might be helpful to handle both this and https://github.com/redhat-openstack/ansible-role-tripleo-gate/issues/1 in a single change that refactors how the repo cloning happens.

**Comment by adarazs** [comment]
Looks like we need to handle 3 types of testing
- manual (we can ask the user to provide a list)
- Zuul based (ZUUL_HOST + ZUUL_CHANGES variable contains all required changes already)
- Jenkins (GERRIT_\* variables and Depends-On in the commit message)

I think we can autodetect the type by looking for the specific env variables.

The manual mode seems simple, I imagine we could have something like this:

``` yaml
artg_change_list:
    - host: ...
      project: ...
      branch: ...
      refspec: ...
    - ...
```

The rest of the modes could parse the changes into the same format.

Parsing the ZUUL_CHANGES looks simple, it has this format: `ZUUL_CHANGES="project1:branch1:refspec1^project2:branch2:refspec2:^..."`

Parsing Depends-On is more involved, but we already have a fairly similar functionality [implemented](https://github.com/redhat-openstack/khaleesi/blob/master/roles/depends-on/files/depends_on.py) in khaleesi, so we could start out from that and return the result as a list of dictionaries.

**Comment by trown** [comment]
I like this approach. I think we would be able to integrate #1 into this quite easily by adding an extra task that has a `when: item.packaging_host is defined`, and then for packaging changes we would just add on to the artg_change_list like:

```
artg_change_list:
  - host: ...
    project: ...
    branch: ...
    refspec: ...
    packaging_host: ...
    packaging_branch: ...
    packaging_refspec: ...
  - ...
```

We could make code changes optional by making the git clone task for code chages have a `when: item.host is defined` as well, but this is not a requirement. I have been just setting the refspec to the branch (ie "master") to get the same behavior.
